name: gradproject
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  animated_text_kit: ^4.2.2
  animate_do: ^2.1.0
  liquid_progress_indicator: ^0.4.0

  curved_navigation_bar: ^1.0.3
  image_picker: ^1.0.1
  path_provider: ^2.0.11
  path: ^1.8.1
  permission_handler: ^10.0.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  pinput: ^5.0.0
  lottie: ^2.7.0
  firebase_messaging: ^15.1.6
  firebase_core: ^3.8.1
  firebase_core_web: ^2.18.2
  firebase_messaging_web: ^3.9.5
  http: ^1.2.2
  excel: ^2.1.0
  csv: ^5.1.1
  file_picker: ^8.1.4
  url_launcher: ^6.1.6
  flutter_svg:  ^1.0.0
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/InterVariable.ttf
    - family: Itim
      fonts:
        - asset: assets/font/Itim-Regular.ttf
  assets:
    - assets/image/
    - assets/image/container/
    - assets/image/sakn/
    - assets/image/slideMenue/
    - assets/image/homeScreen/
    - assets/image/notification/
    - assets/font/
    - assets/file/Attendance.csv
    - assets/image/navBar/
    - assets/image/saknDetails/
    - assets/image/profile/
    - assets/image/sakn/door.png
    - assets/image/sakn/ep_upload-filled.svg
